In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [9]:
# Write your code here
import math

def sigmoid(index):
    return 1 / (1 + math.exp(-index))

Svector = np.vectorize(sigmoid)
Varray = Svector(np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25]))

print(Varray[-5:])

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (x.T).

In [10]:
# Write your code here
x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])
#a)
a=np.multiply(x,y)
print(np.sum(a))
#b)
b=np.dot(x,y)
print(b)
#b)
xT = np.transpose(x) 
c=np.matmul(xT,y)
print(c)


225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [11]:
# Write your code here
x = np.array([1.2,2.3,3.4,-0.7,4.2,2.7,-0.5,1.4,-3.3,0.2])
beta = np.array([2.7,0.33,-2.12,-1.73,2.9,-5.8,-0.9,12.11,3.43,-0.5,-1.65])

#print(np.exp(np.sum(-(x[:9]*beta[:9]))-beta[-1]))

y = 1/(1+np.exp(np.sum(-(x[:10]*beta[:10]))-beta[10]))

print(y)

0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [12]:
# Write your code here
A = np.array([[1,2,1],[3,0,1]])
B = np.array([[0.2],[0.3]])
x1 = np.array([[1,2,3]])
x = x1.T
y = np.dot(A,x)+B
print(y)

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [13]:
# Write your code here
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

## Merge both MovieLens DataFrames into one

In [14]:
# Write your code here
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [15]:
# Write your code here
#steam_df.head(10)
steam_df_copy = steam_df.copy()
chosen_df = steam_df_copy['user-id'].unique()
print(len(chosen_df))

12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [16]:
# Write your code here
chosen_df = steam_df.loc[(steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'purchase'), 
                         ['user-id']]
print(len(chosen_df))

717


**Task 7.** How many purchases people made on average?

In [17]:
# Write your code here
condition = steam_df['behavior-name'] == 'purchase'
chosen_df = steam_df.loc[condition]

condition2 = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), 
                         ['user-id']]
uniqueValues = condition2['user-id'].unique()

print(len(chosen_df)/len(uniqueValues))

10.45033486645687


**Task 8.** Who bought the most games?

In [18]:
# Write your code here
chosen_df = steam_df.loc[(steam_df['behavior-name'] == 'purchase'), 
                         ['user-id']]
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'behavior-name']]
steam_grouped = steam_grouped.groupby('user-id').count()
steam_grouped = steam_grouped.sort_values(by='behavior-name', ascending=False).reset_index()

winner = steam_grouped.head(1)
print(winner.iloc[0]['user-id'])

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [19]:
# Write your code here
steam_grouped = steam_df.loc[(steam_df['game-title'] == 'The Elder Scrolls V Skyrim') & (steam_df['behavior-name'] == 'play'), [ 'value']]
print(steam_grouped['value'].mean())

104.71093057607091


**Task 10.** Which games were played the most (in terms of the number of hours played)? Print the first 10 titles and respective numbers of hours.

In [20]:
# Write your code here
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'play', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').sum()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()
print(steam_grouped.head(10))

                                    game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7


**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print the first 10 titles and respective numbers of hours.

In [21]:
# Write your code here
steam_grouped = steam_df.loc[steam_df['behavior-name'] == 'play', ['game-title', 'value']]
steam_grouped = steam_grouped.groupby('game-title').mean()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()
print(steam_grouped.head(10))

                          game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [40]:
# Write your code here
steam_grouped = steam_df.copy()
steam_grouped['value'] = steam_grouped['value'] - (steam_grouped['behavior-name'] == 'purchase')
steam_grouped = steam_grouped.groupby([
    'game-title', 'user-id'
]).sum().groupby([
    'game-title'
]).mean()
steam_grouped = steam_grouped.sort_values(by='value', ascending=False).reset_index()


print(steam_grouped[['game-title', 'value']].head(10))

                    game-title        value
0      Eastside Hockey Manager  1295.000000
1              FIFA Manager 09   411.000000
2                    Perpetuum   400.975000
3        Football Manager 2012   385.572500
4        Football Manager 2014   382.185000
5        Football Manager 2010   345.439474
6        Football Manager 2011   333.435294
7  Out of the Park Baseball 16   330.400000
8        Football Manager 2013   310.659615
9        Football Manager 2015   307.381013


**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print the first 10 rows from the entire Steam dataset after this change.

In [41]:
# Write your code here
import math

steam_df_copy = steam_df.copy()
steam_df_copy.loc[steam_df_copy['behavior-name'] == 'play',['value']] = steam_df_copy['value'].apply(lambda x: 1/(1+math.exp(-x/100)))

#steam_df_copy['value'] = steam_df_copy['value'].apply(lambda x: 1/(1+math.exp(-x/100)))
print(steam_df_copy.head(10))

     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.704746     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.537181     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.530213     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.522235     0


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [42]:
# Write your code here
ml_grouped = ml_df[['genres','userId']].copy()
#display(ml_grouped)
ml_grouped['genres'] = ml_grouped['genres'].str.split('|')
ml_grouped = ml_grouped.explode('genres')

ml_grouped = ml_grouped.groupby('genres').count()
#display(ml_grouped)
ml_grouped.rename(columns = {'genres':'genre','userId':'n_users'}, inplace = True)
ml_grouped = ml_grouped.sort_values(by='n_users', ascending=False).reset_index()
print(ml_grouped)

                genres  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47


**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [43]:
# Write your code here
ml_grouped = ml_df[['genres','rating']].copy()

ml_grouped['genres'] = ml_grouped['genres'].str.split('|')
ml_grouped = ml_grouped.explode('genres')

ml_grouped = ml_grouped.groupby('genres').mean()

ml_grouped.rename(columns = {'genres':'genre','rating':'rating'}, inplace = True)
ml_grouped = ml_grouped.sort_values(by='rating', ascending=False).reset_index()
print(ml_grouped)

                genres    rating
0            Film-Noir  3.920115
1                  War  3.808294
2          Documentary  3.797785
3                Crime  3.658294
4                Drama  3.656184
5              Mystery  3.632460
6            Animation  3.629937
7                 IMAX  3.618335
8              Western  3.583938
9              Musical  3.563678
10           Adventure  3.508609
11             Romance  3.506511
12            Thriller  3.493706
13             Fantasy  3.491001
14  (no genres listed)  3.489362
15              Sci-Fi  3.455721
16              Action  3.447984
17            Children  3.412956
18              Comedy  3.384721
19              Horror  3.258195


**Task 17.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print first 10 in the form: title, average rating, bias.

In [44]:
# Write your code here
ml_avg = ml_df[['rating']].copy()
ml_avg = ml_avg.mean()[0]


ml_grouped = ml_df[['title','rating']].copy()
ml_grouped = ml_grouped.groupby('title').mean()
ml_grouped['bias'] = ml_grouped['rating']-ml_avg
ml_grouped.rename(columns = {'rating':'average_rating'}, inplace = True)
print(ml_grouped.head(10).reset_index())

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print first 10 in the form: user_id, average rating, bias.

In [45]:
# Write your code here
df_movies = ml_df[['userId', 'rating']]

df_grp_movies = df_movies.groupby(['userId']).agg({
    'rating': 'mean'
}).reset_index()

users_mean_rating = df_movies['rating'].mean()

df_grp_movies['bias'] = df_grp_movies['rating'] - users_mean_rating

df_grp_movies.rename({
    'rating': 'average_rating'
}, axis=1, inplace = True)


print(df_grp_movies.head(10))

   userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task.

In [48]:
# Write your code here
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))


## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix for the MovieLens dataset. Print the submatrix of first 10 rows and 10 columns.

In [33]:
# Write your code here
num_users = ml_df['userId'].max() + 1
num_movies = ml_df['movieId'].max() + 1

inter_mat = np.zeros((num_users, num_movies))

for index, row in ml_df.iterrows():
    user_id = row['userId']
    movie_id = row['movieId']
    inter_mat[user_id][movie_id] = 1

print(inter_mat[:10, :10])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here

**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. To prevent hanging your computer because of RAM shortage use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [ ]:
# Write your code here